// Code generated by hertz generator.

package api

import (
	"context"
	api "github.com/BlueGopher/tiktok-rpc/cmd/api/biz/model/api"
	"github.com/BlueGopher/tiktok-rpc/cmd/api/biz/rpc"
	usercore "github.com/BlueGopher/tiktok-rpc/kitex_gen/userCore"
	"github.com/BlueGopher/tiktok-rpc/pkg/errno"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetUserInfo .
// @router douyin/user [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DouyinUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.DouyinUserResponse)

	c.JSON(consts.StatusOK, resp)
}

// RegisterUser .
// @router douyin/user/register [POST]
func RegisterUser(_ context.Context, c *app.RequestContext) {
	var err error
	var req api.DouyinUserRegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	err = rpc.RegisterUser(context.Background(), &usercore.DouyinUserRegisterRequest{
		Username: req.Username,
		Password: req.Password,
	})
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	SendResponse(c, errno.Success, nil)
}
